version: 2
jobs:

  test-3.6: &full-test-template
    docker:
      - image: circleci/python:3.6-jessie

    steps:
      - checkout

      - restore_cache:
          keys:
            - env-{{ checksum "requirements.txt" }}-{{ checksum "penaltymodel_core/requirements.txt" }}-{{ checksum "penaltymodel_cache/requirements.txt" }}-{{ checksum "penaltymodel_maxgap/requirements.txt" }}-{{ .Environment.CIRCLE_JOB }}

      - run:
          name: create virtual environement
          command: |
            python -m virtualenv env

      - run: &install-requirements-template
          name: install requirements
          command: |
            . env/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./env
          key: env-{{ checksum "requirements.txt" }}-{{ checksum "penaltymodel_core/requirements.txt" }}-{{ checksum "penaltymodel_cache/requirements.txt" }}-{{ checksum "penaltymodel_maxgap/requirements.txt" }}-{{ .Environment.CIRCLE_JOB }}

      - run: &install-ecosystem-template
          name: install penaltymodel ecosystem
          command: |
            . env/bin/activate
            pip install penaltymodel_core/
            pip install penaltymodel_cache/
            pip install penaltymodel_maxgap/

      - run: &core-tests-template
          name: core tests
          command: |
            . env/bin/activate
            coverage run -a -m unittest discover -s penaltymodel_core/
        
      - run: &cache-tests-template
          name: cache tests
          command: |
            . env/bin/activate
            coverage run -a -m unittest discover -s penaltymodel_cache/

      - run: &maxgap-tests-template
          name: maxgap tests
          command: |
            . env/bin/activate
            coverage run -a -m unittest discover -s penaltymodel_maxgap/

      - run: &integration-tests-template
          name: integration tests
          command: |
            . env/bin/activate
            python -m unittest discover

      - run:
          name: doctest
          command: |
            . env/bin/activate
            make -C docs/ doctest

      - run:
          # requires COVERALLS_REPO_TOKEN env variable
          name: coveralls
          command: |
            . env/bin/activate
            if [[ -v COVERALLS_REPO_TOKEN ]]; then coveralls; fi

  test-3.5:
    <<: *full-test-template
    docker:
      - image: circleci/python:3.5-jessie

  test-3.4:
    <<: *full-test-template
    docker:
      - image: circleci/python:3.4-jessie

  test-2.7:
    <<: *full-test-template
    docker:
      - image: circleci/python:2.7-jessie

  test-osx:
    macos:
      xcode: "9.0"

    working_directory: ~/repo

    steps:
      - checkout

      - run: 
          name: install pyenv
          command: |
            brew install pyenv

      - restore_cache:
          keys:
          - pyenv-versions-{{ .Environment.CIRCLE_JOB }}
          - env2.7-{{ checksum "requirements.txt" }}-{{ checksum "penaltymodel_core/requirements.txt" }}-{{ checksum "penaltymodel_cache/requirements.txt" }}-{{ checksum "penaltymodel_maxgap/requirements.txt" }}-{{ .Environment.CIRCLE_JOB }}

      - run:
          name: install python 2.7.14 and 3.6.5 with pyenv
          command: |
            pyenv install 2.7.14 -s
            pyenv install 3.6.5 -s

      - save_cache:
          paths:
            - ~/.pyenv
          key: pyenv-versions-{{ .Environment.CIRCLE_JOB }}

      - run:
          name: create virtualenv for 2.7.14
          command: |
            eval "$(pyenv init -)"
            pyenv local 2.7.14
            python -m pip install virtualenv
            python -m virtualenv env

      - run: *install-requirements-template

      - save_cache:
          paths:
            - ./env
          key: env2.7-{{ checksum "requirements.txt" }}-{{ checksum "penaltymodel_core/requirements.txt" }}-{{ checksum "penaltymodel_cache/requirements.txt" }}-{{ checksum "penaltymodel_maxgap/requirements.txt" }}-{{ .Environment.CIRCLE_JOB }}

      - run: *install-ecosystem-template

      - run: *core-tests-template

      - run: *cache-tests-template

      - run: *maxgap-tests-template

      - run: *integration-tests-template

      - run:
          name: clear virtual environment
          command: |
            rm -rf env

      - restore_cache:
          keys:
          - env3.6-{{ checksum "requirements.txt" }}-{{ checksum "penaltymodel_core/requirements.txt" }}-{{ checksum "penaltymodel_cache/requirements.txt" }}-{{ checksum "penaltymodel_maxgap/requirements.txt" }}-{{ .Environment.CIRCLE_JOB }}

      - run:
          name: create virtualenv for 3.6.5
          command: |
            eval "$(pyenv init -)"
            pyenv local 3.6.5
            python -m pip install virtualenv
            python -m virtualenv env

      - run: *install-requirements-template

      - save_cache:
          paths:
            - ./env
          key: env3.6-{{ checksum "requirements.txt" }}-{{ checksum "penaltymodel_core/requirements.txt" }}-{{ checksum "penaltymodel_cache/requirements.txt" }}-{{ checksum "penaltymodel_maxgap/requirements.txt" }}-{{ .Environment.CIRCLE_JOB }}

      - run: *install-ecosystem-template

      - run: *core-tests-template

      - run: *cache-tests-template

      - run: *maxgap-tests-template

      - run: *integration-tests-template

workflows:
  version: 2
  test:
    jobs:
      - test-3.6
      - test-3.5
      - test-3.4
      - test-2.7
      - test-osx:
          requires:
            - test-3.6
            - test-2.7
            - test-3.5
            - test-3.4
