version: 2.1
jobs:

  test-linux:
    parameters:
      dimod-version:
        type: string
      python-version:
        type: string

    docker:
      - image: circleci/python:<< parameters.python-version >>

    steps:
      - checkout

      - restore_cache:
          keys:
            - env-{{ checksum "requirements.txt" }}-{{ checksum "tests/requirements.txt" }}-{{ checksum "docs/requirements.txt" }}-{{ checksum "penaltymodel_core/requirements.txt" }}-{{ checksum "penaltymodel_cache/requirements.txt" }}-{{ checksum "penaltymodel_maxgap/requirements.txt" }}-{{ checksum "penaltymodel_mip/requirements.txt" }}-{{ checksum "penaltymodel_lp/requirements.txt" }}-{{ .Environment.CIRCLE_JOB }}

      - run: &create-virtualenv-template
          name: create virtual environement
          command: |
            python -m virtualenv env

      - run:
          name: install requirements
          command: |
            . env/bin/activate
            pip install -r requirements.txt -r tests/requirements.txt -r docs/requirements.txt
            pip install --upgrade 'dimod<< parameters.dimod-version >>'

      - save_cache:
          paths:
            - ./env
          key: env-{{ checksum "requirements.txt" }}-{{ checksum "tests/requirements.txt" }}-{{ checksum "docs/requirements.txt" }}-{{ checksum "penaltymodel_core/requirements.txt" }}-{{ checksum "penaltymodel_cache/requirements.txt" }}-{{ checksum "penaltymodel_maxgap/requirements.txt" }}-{{ checksum "penaltymodel_mip/requirements.txt" }}-{{ checksum "penaltymodel_lp/requirements.txt" }}-{{ .Environment.CIRCLE_JOB }}

      - run: &install-core-template
          name: install penaltymodel
          command: |
            . env/bin/activate
            pip install penaltymodel_core/ --no-deps

      - run: &install-cache-template
          name: install penaltymodel-cache
          command: |
            . env/bin/activate
            pip install penaltymodel_cache/ --no-deps

      - run: &install-maxgap-template
          name: install penaltymodel-maxgap
          command: |
            . env/bin/activate
            pip install penaltymodel_maxgap/ --no-deps

      - run: &install-mip-template
          name: install penaltymodel-mip
          command: |
            . env/bin/activate
            pip install penaltymodel_mip/ --no-deps

      - run: &install-lp-template
          name: install penaltymodel-lp
          command: |
            . env/bin/activate
            pip install penaltymodel_lp/ --no-deps

      - run: &core-tests-template
          name: core tests
          command: |
            . env/bin/activate
            coverage run -a -m unittest discover -s penaltymodel_core/

      - run: &cache-tests-template
          name: cache tests
          command: |
            . env/bin/activate
            coverage run -a -m unittest discover -s penaltymodel_cache/

      - run: &maxgap-tests-template
          name: maxgap tests
          command: |
            . env/bin/activate
            coverage run -a -m unittest discover -s penaltymodel_maxgap/

      - run: &lp-tests-template
          name: lp tests
          command: |
            . env/bin/activate
            coverage run -a -m unittest discover -s penaltymodel_lp/

      - run: &mip-tests-template
          name: mip tests
          command: |
            . env/bin/activate
            coverage run -a -m unittest discover -s penaltymodel_mip/

      - run: &integration-tests-template
          name: integration tests
          command: |
            . env/bin/activate
            python -m unittest discover tests/

      - run:
          name: doctest
          command: |
            . env/bin/activate
            make -C docs/ doctest

      - run:
          name: linkcheck
          command: |
            . env/bin/activate
            make -C docs/ linkcheck

      - run:
          name: codecov
          command: |
            . env/bin/activate
            codecov

  #
  # MacOS tests
  #

  test-osx:
    parameters:
      python-version:
        type: string
    macos:
      xcode: 13.2.0
    environment:
      HOMEBREW_NO_AUTO_UPDATE: 1

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: install pyenv
          command: |
            brew install pyenv

      - restore_cache:
          keys:
            - pyenv-{{ .Environment.CIRCLE_JOB }}-xcode-13.2.0

      - when:
          # see https://github.com/pyenv/pyenv/issues/1643. We use an intermediate
          # file so we can use the --skip-existing without raising errors from curl
          condition:
            equal: [3.6.8, << parameters.python-version>>]
          steps:
            - run:
                name: Install Python 3.6 with a patch
                command: |
                  curl -sSL https://github.com/python/cpython/commit/8ea6353.patch > tmp.txt
                  pyenv install -s --patch 3.6.8 < tmp.txt

      - run:
          name: install python
          command: |
            pyenv install << parameters.python-version>> -s

      - save_cache:
          paths:
            - ~/.pyenv
          key: pyenv-{{ .Environment.CIRCLE_JOB }}-xcode-13.2.0

      - run:
          name: create virtualenv
          command: |
            eval "$(pyenv init --path)"
            eval "$(pyenv init -)"
            pyenv local << parameters.python-version >>
            python -m pip install virtualenv
            python -m virtualenv env

      - restore_cache:
          keys:
          - v2-dependencies-{{ checksum "requirements.txt" }}-{{ checksum "tests/requirements.txt" }}-{{ .Environment.CIRCLE_JOB }}

      - run:
          name: install requirements
          command: |
            . env/bin/activate
            pip install -r requirements.txt -r tests/requirements.txt

      - save_cache:
          paths:
            - ./env
          key: v2-dependencies-{{ checksum "requirements.txt" }}-{{ checksum "tests/requirements.txt" }}-{{ .Environment.CIRCLE_JOB }}

      - run: *install-core-template

      - run: *install-cache-template

      - run: *install-maxgap-template

      - run: *install-mip-template

      - run: *install-lp-template

      - run: *core-tests-template

      - run: *cache-tests-template

      - run: *maxgap-tests-template

      - run: *mip-tests-template

      - run: *lp-tests-template

      - run: *integration-tests-template

  deploy-core:
    docker:
      - image: circleci/python:3.6-jessie

    working_directory: ~/repo

    steps:
      - checkout

      - run: *create-virtualenv-template

      - run: *install-core-template

      - run:
          name: verify version matches tag
          command: |
            . env/bin/activate
            [[ "$(pip show penaltymodel 2>/dev/null | grep Version)" == "Version: $(echo "$CIRCLE_TAG" | sed -E 's/core-([0-9]+\.[0-9]+\.[0-9]+(\.dev[0-9]*)?)$/\1/')" ]]

      - run: &pypirc-file-template
          name: init .pypirc
          command: |
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "username = dwtools-ci" >> ~/.pypirc
            echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc
            mkdir dist

      - run:
          name: build sdist and bdist
          command: |
            . env/bin/activate
            cd penaltymodel_core
            python setup.py sdist
            python setup.py bdist_wheel
            mv dist/* ../dist/

      - run: &twine-template
          name: upload
          command: |
            . env/bin/activate
            pip install twine
            twine upload dist/*

  deploy-maxgap:
    docker:
      - image: circleci/python:3.6-jessie

    working_directory: ~/repo

    steps:
      - checkout

      - run: *create-virtualenv-template

      - run: *install-core-template

      - run: *install-maxgap-template

      - run:
          name: verify version matches tag
          command: |
            . env/bin/activate
            [[ "$(pip show penaltymodel-maxgap 2>/dev/null | grep Version)" == "Version: $(echo "$CIRCLE_TAG" | sed -E 's/maxgap-([0-9]+\.[0-9]+\.[0-9]+(\.dev[0-9]*)?)$/\1/')" ]]

      - run: *pypirc-file-template

      - run:
          name: build sdist
          command: |
            . env/bin/activate
            cd penaltymodel_maxgap
            python setup.py sdist
            mv dist/* ../dist/

      - run: *twine-template

  deploy-cache:
    docker:
      - image: circleci/python:3.6-jessie

    working_directory: ~/repo

    steps:
      - checkout

      - run: *create-virtualenv-template

      - run: *install-core-template

      - run: *install-cache-template

      - run:
          name: verify version matches tag
          command: |
            . env/bin/activate
            [[ "$(pip show penaltymodel-cache 2>/dev/null | grep Version)" == "Version: $(echo "$CIRCLE_TAG" | sed -E 's/cache-([0-9]+\.[0-9]+\.[0-9]+(\.dev[0-9]*)?)$/\1/')" ]]

      - run: *pypirc-file-template

      - run:
          name: build bdist and sdist
          command: |
            . env/bin/activate
            cd penaltymodel_cache
            python setup.py sdist
            python setup.py bdist_wheel
            mv dist/* ../dist/

      - run: *twine-template

  deploy-mip:
    docker:
      - image: circleci/python:3.6-jessie

    working_directory: ~/repo

    steps:
      - checkout

      - run: *create-virtualenv-template

      - run: *install-core-template

      - run: *install-mip-template

      - run:
          name: verify version matches tag
          command: |
            . env/bin/activate
            [[ "$(pip show penaltymodel-mip 2>/dev/null | grep Version)" == "Version: $(echo "$CIRCLE_TAG" | sed -E 's/mip-([0-9]+\.[0-9]+\.[0-9]+(\.dev[0-9]*)?)$/\1/')" ]]

      - run: *pypirc-file-template

      - run:
          name: build bdist and sdist
          command: |
            . env/bin/activate
            cd penaltymodel_mip
            python setup.py sdist
            python setup.py bdist_wheel
            mv dist/* ../dist/

      - run: *twine-template

  deploy-lp:
    docker:
      - image: circleci/python:3.6-jessie

    working_directory: ~/repo

    steps:
      - checkout

      - run: *create-virtualenv-template

      - run: *install-core-template

      - run: *install-lp-template

      - run:
          name: verify version matches tag
          command: |
            . env/bin/activate
            [[ "$(pip show penaltymodel-lp 2>/dev/null | grep Version)" == "Version: $(echo "$CIRCLE_TAG" | sed -E 's/lp-([0-9]+\.[0-9]+\.[0-9]+(\.dev[0-9]*)?)$/\1/')" ]]

      - run: *pypirc-file-template

      - run:
          name: build bdist and sdist
          command: |
            . env/bin/activate
            cd penaltymodel_lp
            python setup.py sdist
            python setup.py bdist_wheel
            mv dist/* ../dist/

      - run: *twine-template

workflows:
  version: 2
  test:
    jobs:
      - test-linux:
          name: test-linux-<< matrix.python-version >>-dimod<< matrix.dimod-version >>
          matrix:
            parameters:
              python-version: &python-versions [3.6.8, 3.7.9, 3.8.9, 3.9.4, 3.10.0]
              # 0.8.0 is the smallest supported by all packages
              dimod-version: [==0.8.0, ~=0.9.0, ~=0.10.0]
            exclude:
              - python-version: 3.10.0
                dimod-version: ==0.8.0
              - python-version: 3.10.0
                dimod-version: ~=0.9.0
      - test-osx:
          name: test-osx-<< matrix.python-version >>
          matrix:
            parameters:
              python-version: *python-versions
      - deploy-core:
          filters:
            tags:
              only: /^core-[0-9]+(\.[0-9]+)*(\.dev([0-9]+)?)?$/
            branches:
              ignore: /.*/
      - deploy-cache:
          filters:
            tags:
              only: /^cache-[0-9]+(\.[0-9]+)*(\.dev([0-9]+)?)?$/
            branches:
              ignore: /.*/
      - deploy-maxgap:
          filters:
            tags:
              only: /^maxgap-[0-9]+(\.[0-9]+)*(\.dev([0-9]+)?)?$/
            branches:
              ignore: /.*/
      - deploy-mip:
          filters:
            tags:
              only: /^mip-[0-9]+(\.[0-9]+)*(\.dev([0-9]+)?)?$/
            branches:
              ignore: /.*/
      - deploy-lp:
          filters:
            tags:
              only: /^lp-[0-9]+(\.[0-9]+)*(\.dev([0-9]+)?)?$/
            branches:
              ignore: /.*/
