version: 2
jobs:

  test-3.6: &full-test-template
    docker:
      - image: circleci/python:3.6-jessie

    steps:
      - checkout

      - restore_cache:
          keys:
            - env-{{ checksum "requirements.txt" }}-{{ checksum "penaltymodel_core/requirements.txt" }}-{{ checksum "penaltymodel_cache/requirements.txt" }}-{{ checksum "penaltymodel_maxgap/requirements.txt" }}-{{ .Environment.CIRCLE_JOB }}

      - run:
          name: install requirements
          command: |
            python -m virtualenv env
            . env/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./env
          key: env-{{ checksum "requirements.txt" }}-{{ checksum "penaltymodel_core/requirements.txt" }}-{{ checksum "penaltymodel_cache/requirements.txt" }}-{{ checksum "penaltymodel_maxgap/requirements.txt" }}-{{ .Environment.CIRCLE_JOB }}

      - run:
          name: install penaltymodel ecosystem
          command: |
            . env/bin/activate
            pip install penaltymodel_core/
            pip install penaltymodel_cache/
            pip install penaltymodel_maxgap/

      - run:
          name: core tests
          command: |
            . env/bin/activate
            coverage run -a -m unittest discover -s penaltymodel_core/
        
      - run:
          name: cache tests
          command: |
            . env/bin/activate
            coverage run -a -m unittest discover -s penaltymodel_cache/

      - run:
          name: maxgap tests
          command: |
            . env/bin/activate
            coverage run -a -m unittest discover -s penaltymodel_maxgap/

      - run:
          name: integration tests
          command: |
            . env/bin/activate
            python -m unittest discover

      - run:
          name: doctest
          command: |
            . env/bin/activate
            make -C docs/ doctest

      - run:
          # requires COVERALLS_REPO_TOKEN env variable
          name: coveralls
          command: |
            . env/bin/activate
            if [[ -v COVERALLS_REPO_TOKEN ]]; then coveralls; fi

  test-3.5:
    <<: *full-test-template
    docker:
      - image: circleci/python:3.5-jessie

  test-3.4:
    <<: *full-test-template
    docker:
      - image: circleci/python:3.4-jessie

  test-2.7:
    <<: *full-test-template
    docker:
      - image: circleci/python:2.7-jessie

workflows:
  version: 2
  test:
    jobs:
      - test-3.6
      - test-3.5
      - test-3.4
      - test-2.7
